/*! pandoc-highlighter | (C) 2014 Mike Henderson <mvhenderson@tds.net> | License: MIT */
// Aliases for various CodeMirror mime types
'use strict';

module.exports = {
    aspx:          'application/x-aspx',
    c:             'text/x-c',
    cassandra:     'text/x-cassandra',
    cpp:           'text/x-c++src',
    csharp:        'text/x-csharp',
    cython:        'text/x-cython',
    ejs:           'application/x-ejs',
    erb:           'application/x-erb',
    fragment:      'x-shader/x-fragment',
    fsharp:        'text/x-fsharp',
    hive:          'text/x-hive',
    html:          'htmlmixed',
    hxml:          'text/x-hxml',
    ini:           'text/x-ini',
    java:          'text/x-java',
    json:          'application/json',
    jsp:           'application/x-jsp',
    latex:         'text/x-latex',
    less:          'text/x-less',
    mariadb:       'text/x-mariadb',
    mssql:         'text/x-mssql',
    mysql:         'text/x-mysql',
    ocaml:         'text/x-ocaml',
    plsql:         'text/x-plsql',
    rpmchanges:    'text/x-rpm-changes',
    rpmspec:       'text/x-rpm-spec',
    scala:         'text/x-scala',
    scss:          'text/x-scss',
    sh:            'text/x-sh',
    smarty:        'text/x-smarty',
    sql:           'text/x-sql',
    typescript:    'text/typescript',
    vertex:        'x-shader/x-vertex',
};
